# Generated by Django 4.0.3 on 2023-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnfpostlost', '0003_postlost_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlost_answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postlost_question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
