# Generated by Django 4.0.3 on 2023-12-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lnfpostlost', '0004_postlost_answer_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlost_answer',
            name='voter',
            field=models.ManyToManyField(related_name='postlost_voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlost_question',
            name='voter',
            field=models.ManyToManyField(related_name='postlost_voter_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlost_answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlost_author_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlost_question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlost_author_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
