# Generated by Django 4.0.3 on 2023-12-06 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lnfpost', '0004_postget_answer_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postget_answer',
            name='voter',
            field=models.ManyToManyField(related_name='postget_voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postget_question',
            name='voter',
            field=models.ManyToManyField(related_name='postget_voter_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postget_answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postget_author_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postget_question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postget_author_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
