# Generated by Django 4.0.3 on 2023-12-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lnfpost', '0006_postget_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postget_answer',
            old_name='question',
            new_name='question_postget',
        ),
    ]
