# Generated by Django 4.0.3 on 2023-12-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lnfpost', '0007_rename_question_postget_answer_question_postget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postget_answer',
            old_name='question_postget',
            new_name='question',
        ),
    ]
